# 
os:
  - linux

branches:
  only:
  - master
  - development

before_install:
- sudo apt-get update -qq
- sudo apt-get install --yes git
- sudo apt-get install --yes make
- sudo apt-get install --yes libreadline6-dev
- sudo apt-get install --yes gcc
- sudo apt-get install python2.7-tk
- sudo apt-get install python3-tk
- sudo git clone --recursive https://github.com/jamiejennings/rosie-pattern-language.git /opt/rosie/
- cd /opt/rosie 
- sudo make linux
- sudo make install
- cd $TRAVIS_BUILD_DIR

language: python
python:
   - "2.7"
install: sudo pip install -r ./requirements.txt
script: sudo python ./regression.py